### ISSUE TITLE
Missing genre search

### ISSUE THREAD

**Issue by Aaron-CYF** [Maria-Chira/tv-show-dom-project#3]
> 5. Provide a free-text show search through show names, genres, and summary texts.

This is requirement 5 for level 500 and you cannot search genres on your site, therefore you have not completed level 500.

_Originally posted by @Aaron-CYF in https://github.com/Maria-Chira/tv-show-dom-project/pull/2#discussion_r748626105_

**Comment by Maria-Chira** [comment]
Thanks for your review Aaron. I found your review really helpful. Thanks for spotting the genres and alphabetical issues. I fixed those two along with the other ones mentioned in the comments. You can see the changes in my last commit.
