### ISSUE TITLE
show selector not in alphabetical order

### ISSUE THREAD

**Issue by Aaron-CYF** [Maria-Chira/tv-show-dom-project#4]
> vi. This show select must list shows in alphabetical order, case-insensitive.

This is from requirement 2 for level 400.
Your show selector must be in alphabetical order, therefore you don't met level 400

_Originally posted by @Aaron-CYF in https://github.com/Maria-Chira/tv-show-dom-project/pull/2#discussion_r748644739_

**Comment by Maria-Chira** [comment]
Sorted as mentioned in the previous issue comment.
